platform :ios, '11.0'
swift_version = '5.3'
use_frameworks!

def import_pods
  pod 'SnapKit'
  pod 'BonMot'
  pod 'Kingfisher', '~> 5.0'
  pod 'Alamofire', '~> 5.2'
  pod 'Moya'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'URLNavigator'
end

target 'Day5Sample' do
  import_pods
end
